apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceController.name}}
spec:
  type: LoadBalancer
  ports:
    - name: {{.Values.serviceController.name }}
      port: {{ .Values.serviceController.port }}
      protocol: TCP
      targetPort: {{.Values.serviceController.targetPort }}
  selector:
    app: {{ include "build-cloud-chart.name" . }}