apiVersion: v1
kind: PersistentVolume
metadata:
  name: build-cloud-1-data
spec:
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}
    type: {{ .Values.persistentVolume.hostPathType}}